[tool.poetry]
name = "image-conversion"
version = "0.2.0"
description = ""
authors = ["SWARAJ <bisane.swaraj@gmail.com>"]
readme = "README.md"
packages = [{include = "image_conversion"}]

[tool.poetry.dependencies]
python = "^3.11"
pillow = "^11.1.0"
pillow-heif = "^0.21.0"
tqdm = "^4.67.1"
pyvips = "^3.1.1"

[tool.poetry.group.dev.dependencies]
pre-commit = "^4.5.0"
ipykernel = "^7.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
